=== QusaiiSaleem/scorm-projects/output/njr01-u02-digital-mindset/imscp_rootv1p1p2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- IMS Content Packaging Schema v1.1.2 -->
<!-- Source: IMS Global Learning Consortium -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:imscp="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
            targetNamespace="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
            elementFormDefault="qualified"
            version="1.1.2">

  <xsd:element name="manifest">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="imscp:metadata" minOccurs="0"/>
        <xsd:element ref="imscp:organizations"/>
        <xsd:element ref="imscp:resources"/>
      </xsd:sequence>
      <xsd:attribute name="identifier" type="xsd:ID" use="required"/>
      <xsd:attribute name="version" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="metadata">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="schema" type="xsd:string" minOccurs="0"/>
        <xsd:element name="schemaversion" type="xsd:string" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="organizations">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="imscp:organization" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="default" type="xsd:IDREF"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="organization">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="title" type="xsd:string"/>
        <xsd:element ref="imscp:item" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="identifier" type="xsd:ID" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="item">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="title" type="xsd:string"/>
        <xsd:element ref="imscp:item" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="identifier" type="xsd:ID" use="required"/>
      <xsd:attribute name="identifierref" type="xsd:string"/>
      <xsd:attribute name="isvisible" type="xsd:boolean" default="true"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="resources">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="imscp:resource" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="resource">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="imscp:file" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="imscp:dependency" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="identifier" type="xsd:ID" use="required"/>
      <xsd:attribute name="type" type="xsd:string" use="required"/>
      <xsd:attribute name="href" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="file">
    <xsd:complexType>
      <xsd:attribute name="href" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="dependency">
    <xsd:complexType>
      <xsd:attribute name="identifierref" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== QusaiiSaleem/scorm-projects/output/saudi-foundation-day/imsmanifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest identifier="saudi-foundation-day"
          version="1.0"
          xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
          xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd
                              http://www.adlnet.org/xsd/adlcp_rootv1p2 adlcp_rootv1p2.xsd">

  <!-- Metadata -->
  <metadata>
    <schema>ADL SCORM</schema>
    <schemaversion>1.2</schemaversion>
  </metadata>

  <!-- Organizations -->
  <organizations default="saudi_foundation_day_org">
    <organization identifier="saudi_foundation_day_org">
      <title>يوم التأسيس السعودي</title>

      <item identifier="item_sco_01" identifierref="sco_01_introduction" isvisible="true">
        <title>المقدمة - يوم التأسيس</title>
      </item>

      <item identifier="item_sco_02" identifierref="sco_02_story" isvisible="true">
        <title>قصة التأسيس</title>
      </item>

      <item identifier="item_sco_03" identifierref="sco_03_identity" isvisible="true">
        <title>الهوية والرموز</title>
      </item>

      <item identifier="item_sco_04" identifierref="sco_04_quiz" isvisible="true">
        <title>اختبار المعرفة</title>
      </item>

    </organization>
  </organizations>

  <!-- Resources -->
  <resources>

    <!-- SCO 01: Introduction -->
    <resource identifier="sco_01_introduction"
              type="webcontent"
              adlcp:scormtype="sco"
              href="sco_01_introduction/index.html">
      <file href="sco_01_introduction/index.html"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <!-- SCO 02: Story -->
    <resource identifier="sco_02_story"
              type="webcontent"
              adlcp:scormtype="sco"
              href="sco_02_story/index.html">
      <file href="sco_02_story/index.html"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <!-- SCO 03: Identity -->
    <resource identifier="sco_03_identity"
              type="webcontent"
              adlcp:scormtype="sco"
              href="sco_03_identity/index.html">
      <file href="sco_03_identity/index.html"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <!-- SCO 04: Quiz -->
    <resource identifier="sco_04_quiz"
              type="webcontent"
              adlcp:scormtype="sco"
              href="sco_04_quiz/index.html">
      <file href="sco_04_quiz/index.html"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <!-- Shared Resources -->
    <resource identifier="shared_resources"
              type="webcontent"
              adlcp:scormtype="asset">
      <file href="shared/scorm-api.js"/>
      <file href="shared/base.css"/>
      <file href="shared/theme.css"/>
      <file href="shared/player-shell.css"/>
      <file href="shared/course-custom.css"/>
      <file href="shared/behavior-tracker.js"/>
      <file href="shared/gamification.js"/>
      <file href="shared/engine/slide-controller.js"/>
      <file href="shared/engine/quiz-engine.js"/>
      <file href="shared/assets/icons/arrow-next.svg"/>
      <file href="shared/assets/icons/arrow-prev.svg"/>
      <file href="shared/assets/icons/check-circle.svg"/>
      <file href="shared/assets/icons/info.svg"/>
      <file href="shared/assets/icons/star.svg"/>
      <file href="shared/assets/icons/trophy.svg"/>
      <file href="shared/assets/icons/warning.svg"/>
      <file href="shared/assets/icons/x-circle.svg"/>
    </resource>

  </resources>

</manifest>

=== QusaiiSaleem/scorm-projects/output/njr01-u02-digital-mindset/imsmanifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest identifier="njr01-u02-digital-mindset"
          version="1.0"
          xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
          xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd
                              http://www.adlnet.org/xsd/adlcp_rootv1p2 adlcp_rootv1p2.xsd">

  <metadata>
    <schema>ADL SCORM</schema>
    <schemaversion>1.2</schemaversion>
  </metadata>

  <organizations default="org_njr01_u02">
    <organization identifier="org_njr01_u02">
      <title>الذهنية الرقمية وممارسات الابتكار التقني</title>

      <item identifier="item_sco_01" identifierref="sco_01" isvisible="true">
        <title>مقدمة الوحدة</title>
      </item>

      <item identifier="item_sco_02" identifierref="sco_02" isvisible="true">
        <title>الاختبار القبلي</title>
      </item>

      <item identifier="item_sco_03" identifierref="sco_03" isvisible="true">
        <title>أساسيات الابتكار</title>
      </item>

      <item identifier="item_sco_04" identifierref="sco_04" isvisible="true">
        <title>عقلية الابتكار التقني والتفكير التصميمي</title>
      </item>

      <item identifier="item_sco_05" identifierref="sco_05" isvisible="true">
        <title>من الفكرة إلى السوق</title>
      </item>

      <item identifier="item_sco_06" identifierref="sco_06" isvisible="true">
        <title>الأنشطة التفاعلية</title>
      </item>

      <item identifier="item_sco_07" identifierref="sco_07" isvisible="true">
        <title>الاختبار البعدي</title>
      </item>

    </organization>
  </organizations>

  <resources>

    <resource identifier="sco_01" type="webcontent" adlcp:scormtype="sco" href="sco_01_introduction/index.html">
      <file href="sco_01_introduction/index.html"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <resource identifier="sco_02" type="webcontent" adlcp:scormtype="sco" href="sco_02_pretest/index.html">
      <file href="sco_02_pretest/index.html"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <resource identifier="sco_03" type="webcontent" adlcp:scormtype="sco" href="sco_03_foundations/index.html">
      <file href="sco_03_foundations/index.html"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <resource identifier="sco_04" type="webcontent" adlcp:scormtype="sco" href="sco_04_innovation_mindset/index.html">
      <file href="sco_04_innovation_mindset/index.html"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <resource identifier="sco_05" type="webcontent" adlcp:scormtype="sco" href="sco_05_idea_to_market/index.html">
      <file href="sco_05_idea_to_market/index.html"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <resource identifier="sco_06" type="webcontent" adlcp:scormtype="sco" href="sco_06_activities/index.html">
      <file href="sco_06_activities/index.html"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <resource identifier="sco_07" type="webcontent" adlcp:scormtype="sco" href="sco_07_posttest/index.html">
      <file href="sco_07_posttest/index.html"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <resource identifier="shared_resources" type="webcontent" adlcp:scormtype="asset">
      <file href="shared/scorm-api.js"/>
      <file href="shared/behavior-tracker.js"/>
      <file href="shared/gamification.js"/>
      <file href="shared/base.css"/>
      <file href="shared/player-shell.css"/>
      <file href="shared/theme.css"/>
      <file href="shared/course-custom.css"/>
      <file href="shared/engine/slide-controller.js"/>
      <file href="shared/engine/quiz-engine.js"/>
      <file href="shared/engine/player-shell.js"/>
      <file href="shared/engine/state-engine.js"/>
      <file href="shared/engine/trigger-engine.js"/>
      <file href="shared/engine/variable-store.js"/>
      <file href="shared/engine/sound-effects.js"/>
      <file href="shared/engine/confetti.js"/>
      <file href="shared/engine/achievement-system.js"/>
      <file href="shared/assets/icons/arrow-next.svg"/>
      <file href="shared/assets/icons/arrow-prev.svg"/>
      <file href="shared/assets/icons/check-circle.svg"/>
      <file href="shared/assets/icons/info.svg"/>
      <file href="shared/assets/icons/star.svg"/>
      <file href="shared/assets/icons/trophy.svg"/>
      <file href="shared/assets/icons/warning.svg"/>
      <file href="shared/assets/icons/x-circle.svg"/>
    </resource>

  </resources>

</manifest>

=== QusaiiSaleem/scorm-projects/output/njr01-u03/imsmanifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest identifier="NJR01_U03_data_mindset"
          version="1.0"
          xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
          xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd
                              http://www.adlnet.org/xsd/adlcp_rootv1p2 adlcp_rootv1p2.xsd">

  <metadata>
    <schema>ADL SCORM</schema>
    <schemaversion>1.2</schemaversion>
  </metadata>

  <organizations default="org_njr01_u03">
    <organization identifier="org_njr01_u03">
      <title>عقلية البيانات: التعلم والتواصل باستخدام البيانات</title>

      <item identifier="item_sco_01" identifierref="sco_01" isvisible="true">
        <title>المقدمة والأهداف التعليمية</title>
      </item>

      <item identifier="item_sco_02" identifierref="sco_02" isvisible="true">
        <title>مقدمة عن عقلية البيانات</title>
      </item>

      <item identifier="item_sco_03" identifierref="sco_03" isvisible="true">
        <title>البيانات الضخمة</title>
      </item>

      <item identifier="item_sco_04" identifierref="sco_04" isvisible="true">
        <title>أهمية البيانات في حياتنا</title>
      </item>

      <item identifier="item_sco_05" identifierref="sco_05" isvisible="true">
        <title>جودة البيانات</title>
      </item>

      <item identifier="item_sco_06" identifierref="sco_06" isvisible="true">
        <title>التواصل باستخدام البيانات</title>
      </item>

      <item identifier="item_sco_07" identifierref="sco_07" isvisible="true">
        <title>الخصوصية والملخص</title>
      </item>

    </organization>
  </organizations>

  <resources>

    <resource identifier="sco_01" type="webcontent" adlcp:scormtype="sco" href="sco_01_intro/index.html">
      <file href="sco_01_intro/index.html"/>
      <file href="sco_01_intro/content.js"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <resource identifier="sco_02" type="webcontent" adlcp:scormtype="sco" href="sco_02_data_mindset/index.html">
      <file href="sco_02_data_mindset/index.html"/>
      <file href="sco_02_data_mindset/content.js"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <resource identifier="sco_03" type="webcontent" adlcp:scormtype="sco" href="sco_03_big_data/index.html">
      <file href="sco_03_big_data/index.html"/>
      <file href="sco_03_big_data/content.js"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <resource identifier="sco_04" type="webcontent" adlcp:scormtype="sco" href="sco_04_data_importance/index.html">
      <file href="sco_04_data_importance/index.html"/>
      <file href="sco_04_data_importance/content.js"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <resource identifier="sco_05" type="webcontent" adlcp:scormtype="sco" href="sco_05_data_quality/index.html">
      <file href="sco_05_data_quality/index.html"/>
      <file href="sco_05_data_quality/content.js"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <resource identifier="sco_06" type="webcontent" adlcp:scormtype="sco" href="sco_06_communication/index.html">
      <file href="sco_06_communication/index.html"/>
      <file href="sco_06_communication/content.js"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <resource identifier="sco_07" type="webcontent" adlcp:scormtype="sco" href="sco_07_privacy_summary/index.html">
      <file href="sco_07_privacy_summary/index.html"/>
      <file href="sco_07_privacy_summary/content.js"/>
      <dependency identifierref="shared_resources"/>
    </resource>

    <resource identifier="shared_resources" type="webcontent" adlcp:scormtype="asset">
      <file href="shared/scorm-api.js"/>
      <file href="shared/behavior-tracker.js"/>
      <file href="shared/gamification.js"/>
      <file href="shared/base.css"/>
      <file href="shared/player-shell.css"/>
      <file href="shared/theme.css"/>
      <file href="shared/course-custom.css"/>
      <file href="shared/engine/slide-controller.js"/>
      <file href="shared/engine/quiz-engine.js"/>
      <file href="shared/engine/state-engine.js"/>
      <file href="shared/engine/interactivity-engine.js"/>
      <file href="shared/engine/confetti.js"/>
      <file href="shared/engine/achievement-system.js"/>
      <file href="shared/engine/sound-effects.js"/>
      <file href="shared/assets/fonts/Tajawal-Regular.ttf"/>
      <file href="shared/assets/fonts/Tajawal-Medium.ttf"/>
      <file href="shared/assets/fonts/Tajawal-Bold.ttf"/>
      <file href="shared/assets/fonts/Tajawal-ExtraBold.ttf"/>
      <file href="shared/assets/icons/arrow-next.svg"/>
      <file href="shared/assets/icons/arrow-prev.svg"/>
      <file href="shared/assets/icons/check-circle.svg"/>
      <file href="shared/assets/icons/info.svg"/>
      <file href="shared/assets/icons/warning.svg"/>
      <file href="shared/assets/icons/star.svg"/>
      <file href="shared/assets/icons/trophy.svg"/>
      <file href="shared/assets/icons/x-circle.svg"/>
    </resource>

  </resources>

</manifest>
